### ISSUE TITLE
channel_bench_mob.py

### ISSUE THREAD

**Issue by hafizuriu** [mingkai-zheng/GENIUS#2]
You're doing really a great job.

I have some queries in your code.

```benchmark_file = open('benchmark/Results_MobileNet.json')
data = json.load(benchmark_file)
keys = list(data.keys())
rank = np.array([data[k]['mean'] for k in keys]).argsort().argsort()
for k, r in zip(keys, rank):
    data[k]['rank'] = (4 ** 7) - r

res = openai.ChatCompletion.create(model='gpt-4', messages=messages, temperature=0, n=1)['choices'][0]['message']
messages.append(res)
messages_history.append(messages)

# print(messages)
print(res['content'])

channels = json.loads(res['content'])
search_id = ''.join([str(int(c / base_c)) for base_c, c in zip(base_channels, channels)])
accuracy = data[search_id]['mean']
accuracy = float(Decimal(accuracy).quantize(Decimal("0.01"), rounding = "ROUND_HALF_UP"))

```

I have seen the _benchmark/Results_MobileNet.json_ file where accuracy values are stored. 
Can you please explain how can you get the accuracy and gave feedback to GPT-4?

**Comment by mingkai-zheng** [comment]
The architecture string is determined by the ratio of channel_size to base_channel. Referring to the channel_bench_mob.py file (found [here](https://github.com/mingkai-zheng/GENIUS/blob/97361d30b2da337edd0c8e1ed71b7c88b4a85d38/channel_bench_mob.py#L100)), you can see a variable named base_channels. Suppose the architecture has the following channel configuration for each layer:
```
{
    channels[0]: 64,
    channels[1]: 384,
    channels[2]: 768,
    channels[3]: 192,
    channels[4]: 64,
    channels[5]: 1152,
    channels[6]: 512,
}
```
And the base_channels are:
```base_channels = [32, 192, 192, 192, 64, 384, 256]```
Given this, the architecture string would be ```2241132```, as the ratios are calculated as follows: ```64/32=2, 384/192=2, 768/192=4, and so on.```
